### ISSUE TITLE
Segfault in test case fsolver_Temp.solve on aarch64

### ISSUE THREAD

**Issue by jzarl** [Reoptimize-Systems/xfemm#3]
Backtrace as posted to the mailing list:
````
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-unknown-openbsd6.8".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../../../bin/fsolver...done.
[New process 458031]
Core was generated by `fsolver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000001d8fc3bfac in FEASolver<femm::CMPointProp, femm::CMBoundaryProp, femm::CMSolverMaterialProp, femm::CMCircuit, femm::CMBlockLabel, femmsolver::CMElement>::Cuthill (this=0x7fffff0cd8, deletefiles=true)
    at /home/alexshendi/sources/packages/xfemm/cfemm/fsolver/../libfemm/cuthill.cpp:283
283                             agelist[i].quadNode[k].n2=newnum[agelist[i].quadNode[k].n2];
(gdb) bt
#0  0x0000001d8fc3bfac in FEASolver<femm::CMPointProp, femm::CMBoundaryProp, femm::CMSolverMaterialProp, femm::CMCircuit, femm::CMBlockLabel, femmsolver::CMElement>::Cuthill (this=0x7fffff0cd8, deletefiles=true)
    at /home/alexshendi/sources/packages/xfemm/cfemm/fsolver/../libfemm/cuthill.cpp:283
#1  0x0000001d8fc39eb0 in FSolver::runSolver (this=0x7fffff0cd8, verbose=true)
    at /home/alexshendi/sources/packages/xfemm/cfemm/fsolver/fsolver.cpp:1192
#2  0x0000001d8fc35c38 in main (argc=2, argv=0x7fffff0f78)
    at /home/alexshendi/sources/packages/xfemm/cfemm/fsolver/main.cpp:80
(gdb) q
````

**Comment by reos-rcrozier** [comment]
This issue occured when an input file was used which did not have the right number of values in the AGE description line. In  https://github.com/Reoptimize-Systems/xfemm/commit/a6976dc977ae3a3c2bfe8295959a7a68411740dc I added checks when loading the file so it's caught earlier and the user is warned about the failure.
